import ContainerTagLinks from "@/components/ContainerTagLInk";
import Header from "@/components/Header";
import { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "swiper/css";
import "./globals.scss";

const roboto = Roboto_Mono({ subsets: ["latin"], weight: ["400", "700"] });
export const metadata: Metadata = {
  title: "Erick Staviasz",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=1"],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} text-gray`}>
        <Header />
        <ContainerTagLinks />
        {children}
      </body>
    </html>
  );
}
